// Generated by drizzle-kit — do not edit manually
// Run `npm run db:generate` to regenerate
export default {
  journal: {
    entries: [
      {
        idx: 0,
        version: '6',
        when: 1775144480737,
        tag: '0000_lame_stone_men',
        breakpoints: true,
      },
    ],
  },
  migrations: {
    '0000_lame_stone_men': `CREATE TABLE \`items\` (
\t\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
\t\`remote_id\` integer,
\t\`list_id\` integer NOT NULL,
\t\`description\` text NOT NULL,
\t\`checked\` integer DEFAULT false NOT NULL,
\t\`quantity\` text,
\t\`price\` real,
\t\`updated_at\` integer NOT NULL,
\t\`deleted_at\` integer,
\tFOREIGN KEY (\`list_id\`) REFERENCES \`lists\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`lists\` (
\t\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
\t\`remote_id\` integer,
\t\`name\` text NOT NULL,
\t\`updated_at\` integer NOT NULL,
\t\`deleted_at\` integer
);
--> statement-breakpoint
CREATE TABLE \`sync_queue\` (
\t\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
\t\`entity\` text NOT NULL,
\t\`operation\` text NOT NULL,
\t\`payload\` text NOT NULL,
\t\`created_at\` integer NOT NULL,
\t\`retry_count\` integer DEFAULT 0 NOT NULL,
\t\`last_error\` text
);
`,
  },
};
