// Generated by drizzle-kit — do not edit manually
// Run `npm run db:generate` to regenerate
export default {
  journal: {
    entries: [
      {
        idx: 0,
        version: '6',
        when: 1775144480737,
        tag: '0000_lame_stone_men',
        breakpoints: true,
      },
      {
        idx: 1,
        version: '6',
        when: 1775144480738,
        tag: '0001_quantity_real_uom',
        breakpoints: true,
      },
    ],
  },
  migrations: {
    m0000: `CREATE TABLE \`items\` (
\t\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
\t\`remote_id\` integer,
\t\`list_id\` integer NOT NULL,
\t\`description\` text NOT NULL,
\t\`checked\` integer DEFAULT false NOT NULL,
\t\`quantity\` text,
\t\`price\` real,
\t\`updated_at\` integer NOT NULL,
\t\`deleted_at\` integer,
\tFOREIGN KEY (\`list_id\`) REFERENCES \`lists\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`lists\` (
\t\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
\t\`remote_id\` integer,
\t\`name\` text NOT NULL,
\t\`updated_at\` integer NOT NULL,
\t\`deleted_at\` integer
);
--> statement-breakpoint
CREATE TABLE \`sync_queue\` (
\t\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
\t\`entity\` text NOT NULL,
\t\`operation\` text NOT NULL,
\t\`payload\` text NOT NULL,
\t\`created_at\` integer NOT NULL,
\t\`retry_count\` integer DEFAULT 0 NOT NULL,
\t\`last_error\` text
);
`,
    m0001: `PRAGMA foreign_keys=OFF;
--> statement-breakpoint
CREATE TABLE \`__new_items\` (
\t\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
\t\`remote_id\` integer,
\t\`list_id\` integer NOT NULL,
\t\`description\` text NOT NULL,
\t\`checked\` integer DEFAULT false NOT NULL,
\t\`quantity\` real,
\t\`price\` real,
\t\`uom\` text,
\t\`updated_at\` integer NOT NULL,
\t\`deleted_at\` integer,
\tFOREIGN KEY (\`list_id\`) REFERENCES \`lists\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO \`__new_items\` SELECT \`id\`, \`remote_id\`, \`list_id\`, \`description\`, \`checked\`, CAST(\`quantity\` AS REAL), \`price\`, NULL, \`updated_at\`, \`deleted_at\` FROM \`items\`;
--> statement-breakpoint
DROP TABLE \`items\`;
--> statement-breakpoint
ALTER TABLE \`__new_items\` RENAME TO \`items\`;
--> statement-breakpoint
PRAGMA foreign_keys=ON;`,
  },
};
